name: Build java package

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push: # Apply to all branches

env:
  CHANGELIST: -SNAPSHOT
  RELEASE_VERSION: 0.0.0

jobs:
  test-java-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Retrieve current version from gradle.properties
        run: |
          ./gradlew properties --no-daemon --build-cache --info